language: python
sudo: false

matrix:
    include:
    - python: 2.7
      env: TOXENV=py27

before_install:
    - python -m pip install --upgrade setuptools pip virtualenv pytest

# command to install dependencies
install:
    - pip install -r requirements.txt

# command to run tests
script:
     - pytest -s -vvvv EC2

